name: Deploy Redis Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy Redis JAR and config locally, restart PM2
        env:
          REMOTE_PATH: /home/jayakumar/jenkins_projects/redis
          JAR_NAME: redis-0.0.1-SNAPSHOT.jar
          CONFIG_FILE: application.properties
          SERVICE_NAME: Redis
        run: |
          echo "Copying JAR and config to deployment path..."
          mv $REMOTE_PATH/$JAR_NAME $REMOTE_PATH/backup/${JAR_NAME%.jar}_$TIMESTAMP.jar
          cp target/$JAR_NAME $REMOTE_PATH/

          echo "Restarting Redis service with PM2..."
          pm2 restart $SERVICE_NAME
          pm2 save
